-- Add missing columns to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'beverage',
ADD COLUMN IF NOT EXISTS subcategory TEXT,
ADD COLUMN IF NOT EXISTS brand TEXT DEFAULT 'krak',
ADD COLUMN IF NOT EXISTS "unitWeight" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "unitVolume" INTEGER,
ADD COLUMN IF NOT EXISTS "costPrice" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'USD',
ADD COLUMN IF NOT EXISTS "isBundle" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP;